FROM centos:latest

RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN rpm -iUvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
RUN yum -y update
